import type { BasicFormValues } from '@/lib/basicFormMapping';

export type StarterTemplate = Readonly<{
  id:
    | 'brokerage-bridge-72t'
    | 'roth-ladder'
    | 'ltcg-harvest'
    | 'aca-optimized'
    | 'conservative-no-customlaw'
    | 'bay-area-early-retiree';
  label: string;
  shortDescription: string;
  longDescription: string;
  formValues: BasicFormValues;
}>;

export const STARTER_TEMPLATES = [
  {
    id: 'brokerage-bridge-72t',
    label: 'Brokerage bridge with 72(t) context',
    shortDescription: 'A 10-year taxable brokerage bridge for an early-retired MFJ household.',
    longDescription:
      'Models the spreadsheet-style 72(t) example as a 10-year auto-deplete taxable brokerage bridge with ACA years before later Social Security income. Phase 1B does not introduce a separate 72(t) SEPP withdrawal stream into projection; the template uses the existing basic-form fields to show the bridge-year cash-flow tradeoff.',
    formValues: {
      currentYear: 2026,
      filingStatus: 'mfj',
      stateCode: 'FL',
      primaryAge: 55,
      partnerAge: 55,
      retirementYear: 2026,
      planEndAge: 95,
      annualSpendingToday: 90_000,
      inflationRate: 0.025,
      annualMortgagePAndI: 0,
      mortgagePayoffYear: 0,
      annualW2Income: 0,
      annualContributionTraditional: 0,
      annualContributionRoth: 0,
      annualContributionHsa: 0,
      annualContributionBrokerage: 0,
      annualConsultingIncome: 0,
      annualRentalIncome: 0,
      annualSocialSecurityBenefit: 52_000,
      socialSecurityClaimAge: 67,
      annualPensionOrAnnuityIncome: 0,
      brokerageAndCashBalance: 675_000,
      taxableBrokerageBasis: 520_000,
      hsaBalance: 25_000,
      traditionalBalance: 1_650_000,
      rothBalance: 360_000,
      startingRothContributionBasis: 360_000,
      autoDepleteBrokerageEnabled: true,
      autoDepleteBrokerageYears: 10,
      autoDepleteBrokerageAnnualScaleUpFactor: 0.02,
      expectedReturnTraditional: 0.05,
      expectedReturnRoth: 0.05,
      expectedReturnBrokerage: 0.04,
      expectedReturnHsa: 0.04,
      brokerageDividendYield: 0.015,
      brokerageQdiPercentage: 0.95,
      healthcarePhase: 'aca',
    },
  },
  {
    id: 'roth-ladder',
    label: 'Roth ladder bridge',
    shortDescription: 'A 5-year taxable brokerage bridge around a Roth conversion ladder strategy.',
    longDescription:
      'Frames the Roth ladder example as five early bridge years funded from taxable brokerage while traditional IRA assets remain available for conversion planning. It highlights the tradeoff between preserving ACA-friendly income and leaving enough brokerage liquidity before later Social Security income begins.',
    formValues: {
      currentYear: 2026,
      filingStatus: 'mfj',
      stateCode: 'PA',
      primaryAge: 50,
      partnerAge: 49,
      retirementYear: 2026,
      planEndAge: 95,
      annualSpendingToday: 82_000,
      inflationRate: 0.025,
      annualMortgagePAndI: 18_000,
      mortgagePayoffYear: 2030,
      annualW2Income: 0,
      annualContributionTraditional: 0,
      annualContributionRoth: 0,
      annualContributionHsa: 0,
      annualContributionBrokerage: 0,
      annualConsultingIncome: 0,
      annualRentalIncome: 0,
      annualSocialSecurityBenefit: 58_000,
      socialSecurityClaimAge: 70,
      annualPensionOrAnnuityIncome: 0,
      brokerageAndCashBalance: 625_000,
      taxableBrokerageBasis: 500_000,
      hsaBalance: 35_000,
      traditionalBalance: 1_550_000,
      rothBalance: 520_000,
      startingRothContributionBasis: 520_000,
      autoDepleteBrokerageEnabled: true,
      autoDepleteBrokerageYears: 5,
      autoDepleteBrokerageAnnualScaleUpFactor: 0.03,
      expectedReturnTraditional: 0.05,
      expectedReturnRoth: 0.05,
      expectedReturnBrokerage: 0.04,
      expectedReturnHsa: 0.04,
      brokerageDividendYield: 0.0125,
      brokerageQdiPercentage: 0.95,
      healthcarePhase: 'aca',
    },
  },
  {
    id: 'ltcg-harvest',
    label: 'LTCG harvest bridge',
    shortDescription: 'A taxable-heavy MFJ case designed around opportunistic gain harvesting.',
    longDescription:
      'Large unrealized gains in brokerage. Strategy: stay inside the 0% LTCG bracket as long as possible while harvesting gains opportunistically.',
    formValues: {
      currentYear: 2026,
      filingStatus: 'mfj',
      stateCode: 'FL',
      primaryAge: 50,
      partnerAge: 50,
      retirementYear: 2026,
      planEndAge: 95,
      annualSpendingToday: 80_000,
      inflationRate: 0.025,
      annualMortgagePAndI: 0,
      mortgagePayoffYear: 0,
      annualW2Income: 0,
      annualContributionTraditional: 0,
      annualContributionRoth: 0,
      annualContributionHsa: 0,
      annualContributionBrokerage: 0,
      annualConsultingIncome: 0,
      annualRentalIncome: 0,
      annualSocialSecurityBenefit: 25_000,
      socialSecurityClaimAge: 67,
      annualPensionOrAnnuityIncome: 0,
      brokerageAndCashBalance: 1_200_000,
      taxableBrokerageBasis: 400_000,
      hsaBalance: 30_000,
      traditionalBalance: 400_000,
      rothBalance: 50_000,
      startingRothContributionBasis: 50_000,
      autoDepleteBrokerageEnabled: true,
      autoDepleteBrokerageYears: 15,
      autoDepleteBrokerageAnnualScaleUpFactor: 0.02,
      expectedReturnTraditional: 0.05,
      expectedReturnRoth: 0.05,
      expectedReturnBrokerage: 0.05,
      expectedReturnHsa: 0.05,
      brokerageDividendYield: 0.014,
      brokerageQdiPercentage: 0.95,
      healthcarePhase: 'aca',
    },
  },
  {
    id: 'aca-optimized',
    label: 'ACA-optimized bridge',
    shortDescription: 'A trad-heavy MFJ plan with limited brokerage runway and conservative draws.',
    longDescription:
      'Trad-heavy with limited brokerage runway. Conservative draws keep MAGI in the 200-400% FPL band for maximum ACA subsidy.',
    formValues: {
      currentYear: 2026,
      filingStatus: 'mfj',
      stateCode: 'FL',
      primaryAge: 55,
      partnerAge: 55,
      retirementYear: 2027,
      planEndAge: 90,
      annualSpendingToday: 60_000,
      inflationRate: 0.025,
      annualMortgagePAndI: 0,
      mortgagePayoffYear: 0,
      annualW2Income: 0,
      annualContributionTraditional: 0,
      annualContributionRoth: 0,
      annualContributionHsa: 0,
      annualContributionBrokerage: 0,
      annualConsultingIncome: 0,
      annualRentalIncome: 0,
      annualSocialSecurityBenefit: 35_000,
      socialSecurityClaimAge: 70,
      annualPensionOrAnnuityIncome: 0,
      brokerageAndCashBalance: 200_000,
      taxableBrokerageBasis: 150_000,
      hsaBalance: 40_000,
      traditionalBalance: 1_500_000,
      rothBalance: 300_000,
      startingRothContributionBasis: 300_000,
      autoDepleteBrokerageEnabled: true,
      autoDepleteBrokerageYears: 8,
      autoDepleteBrokerageAnnualScaleUpFactor: 0.015,
      expectedReturnTraditional: 0.04,
      expectedReturnRoth: 0.04,
      expectedReturnBrokerage: 0.04,
      expectedReturnHsa: 0.04,
      brokerageDividendYield: 0.015,
      brokerageQdiPercentage: 0.9,
      healthcarePhase: 'aca',
    },
  },
  {
    id: 'conservative-no-customlaw',
    label: 'Conservative current-law',
    shortDescription: 'A single-filer case near Medicare age with explicit manual control.',
    longDescription:
      "Single filer near Medicare-eligibility, no auto-deplete (you'll set explicit withdrawals in advanced mode). Tight spending, conservative returns.",
    formValues: {
      currentYear: 2026,
      filingStatus: 'single',
      stateCode: 'FL',
      primaryAge: 60,
      partnerAge: 60,
      retirementYear: 2026,
      planEndAge: 95,
      annualSpendingToday: 55_000,
      inflationRate: 0.025,
      annualMortgagePAndI: 12_000,
      mortgagePayoffYear: 2028,
      annualW2Income: 0,
      annualContributionTraditional: 0,
      annualContributionRoth: 0,
      annualContributionHsa: 0,
      annualContributionBrokerage: 0,
      annualConsultingIncome: 0,
      annualRentalIncome: 0,
      annualSocialSecurityBenefit: 40_000,
      socialSecurityClaimAge: 67,
      annualPensionOrAnnuityIncome: 0,
      brokerageAndCashBalance: 500_000,
      taxableBrokerageBasis: 350_000,
      hsaBalance: 25_000,
      traditionalBalance: 700_000,
      rothBalance: 200_000,
      startingRothContributionBasis: 200_000,
      autoDepleteBrokerageEnabled: false,
      autoDepleteBrokerageYears: 10,
      autoDepleteBrokerageAnnualScaleUpFactor: 0.02,
      expectedReturnTraditional: 0.04,
      expectedReturnRoth: 0.04,
      expectedReturnBrokerage: 0.04,
      expectedReturnHsa: 0.04,
      brokerageDividendYield: 0.014,
      brokerageQdiPercentage: 0.95,
      healthcarePhase: 'aca',
    },
  },
  {
    id: 'bay-area-early-retiree',
    label: 'Bay Area early retiree',
    shortDescription: 'A California MFJ household retiring in the mid-50s with higher local spending.',
    longDescription:
      'Bay Area parity scenario for an early-retiree household leaving W-2 income around age 55. It keeps the model in basic-form data while testing California taxes, ACA years, and a higher spending baseline.',
    formValues: {
      currentYear: 2026,
      filingStatus: 'mfj',
      stateCode: 'CA',
      primaryAge: 53,
      partnerAge: 53,
      retirementYear: 2028,
      planEndAge: 95,
      annualSpendingToday: 150_000,
      inflationRate: 0.025,
      annualMortgagePAndI: 0,
      mortgagePayoffYear: 0,
      annualW2Income: 450_000,
      annualContributionTraditional: 0,
      annualContributionRoth: 0,
      annualContributionHsa: 0,
      annualContributionBrokerage: 0,
      annualConsultingIncome: 0,
      annualRentalIncome: 0,
      annualSocialSecurityBenefit: 72_000,
      socialSecurityClaimAge: 70,
      annualPensionOrAnnuityIncome: 0,
      brokerageAndCashBalance: 1_800_000,
      taxableBrokerageBasis: 1_200_000,
      hsaBalance: 100_000,
      traditionalBalance: 1_600_000,
      rothBalance: 850_000,
      startingRothContributionBasis: 850_000,
      autoDepleteBrokerageEnabled: true,
      autoDepleteBrokerageYears: 8,
      autoDepleteBrokerageAnnualScaleUpFactor: 0.025,
      expectedReturnTraditional: 0.05,
      expectedReturnRoth: 0.05,
      expectedReturnBrokerage: 0.045,
      expectedReturnHsa: 0.05,
      brokerageDividendYield: 0.012,
      brokerageQdiPercentage: 0.95,
      healthcarePhase: 'aca',
    },
  },
] as const satisfies readonly StarterTemplate[];
